/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalonRouteImport } from './routes/salon'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalonIndexRouteImport } from './routes/salon.index'
import { Route as SalonWalletRouteImport } from './routes/salon.wallet'
import { Route as SalonStaffRouteImport } from './routes/salon.staff'
import { Route as SalonSettingsRouteImport } from './routes/salon.settings'
import { Route as SalonServicesRouteImport } from './routes/salon.services'
import { Route as SalonProfileRouteImport } from './routes/salon.profile'
import { Route as SalonPrivacyPolicyRouteImport } from './routes/salon.privacy-policy'
import { Route as SalonHelpSupportRouteImport } from './routes/salon.help-support'
import { Route as SalonGalleryRouteImport } from './routes/salon.gallery'
import { Route as SalonBookingsRouteImport } from './routes/salon.bookings'

const SalonRoute = SalonRouteImport.update({
  id: '/salon',
  path: '/salon',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonIndexRoute = SalonIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalonRoute,
} as any)
const SalonWalletRoute = SalonWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => SalonRoute,
} as any)
const SalonStaffRoute = SalonStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => SalonRoute,
} as any)
const SalonSettingsRoute = SalonSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SalonRoute,
} as any)
const SalonServicesRoute = SalonServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SalonRoute,
} as any)
const SalonProfileRoute = SalonProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SalonRoute,
} as any)
const SalonPrivacyPolicyRoute = SalonPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => SalonRoute,
} as any)
const SalonHelpSupportRoute = SalonHelpSupportRouteImport.update({
  id: '/help-support',
  path: '/help-support',
  getParentRoute: () => SalonRoute,
} as any)
const SalonGalleryRoute = SalonGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SalonRoute,
} as any)
const SalonBookingsRoute = SalonBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => SalonRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/salon': typeof SalonRouteWithChildren
  '/salon/bookings': typeof SalonBookingsRoute
  '/salon/gallery': typeof SalonGalleryRoute
  '/salon/help-support': typeof SalonHelpSupportRoute
  '/salon/privacy-policy': typeof SalonPrivacyPolicyRoute
  '/salon/profile': typeof SalonProfileRoute
  '/salon/services': typeof SalonServicesRoute
  '/salon/settings': typeof SalonSettingsRoute
  '/salon/staff': typeof SalonStaffRoute
  '/salon/wallet': typeof SalonWalletRoute
  '/salon/': typeof SalonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/salon/bookings': typeof SalonBookingsRoute
  '/salon/gallery': typeof SalonGalleryRoute
  '/salon/help-support': typeof SalonHelpSupportRoute
  '/salon/privacy-policy': typeof SalonPrivacyPolicyRoute
  '/salon/profile': typeof SalonProfileRoute
  '/salon/services': typeof SalonServicesRoute
  '/salon/settings': typeof SalonSettingsRoute
  '/salon/staff': typeof SalonStaffRoute
  '/salon/wallet': typeof SalonWalletRoute
  '/salon': typeof SalonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/salon': typeof SalonRouteWithChildren
  '/salon/bookings': typeof SalonBookingsRoute
  '/salon/gallery': typeof SalonGalleryRoute
  '/salon/help-support': typeof SalonHelpSupportRoute
  '/salon/privacy-policy': typeof SalonPrivacyPolicyRoute
  '/salon/profile': typeof SalonProfileRoute
  '/salon/services': typeof SalonServicesRoute
  '/salon/settings': typeof SalonSettingsRoute
  '/salon/staff': typeof SalonStaffRoute
  '/salon/wallet': typeof SalonWalletRoute
  '/salon/': typeof SalonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/salon'
    | '/salon/bookings'
    | '/salon/gallery'
    | '/salon/help-support'
    | '/salon/privacy-policy'
    | '/salon/profile'
    | '/salon/services'
    | '/salon/settings'
    | '/salon/staff'
    | '/salon/wallet'
    | '/salon/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/salon/bookings'
    | '/salon/gallery'
    | '/salon/help-support'
    | '/salon/privacy-policy'
    | '/salon/profile'
    | '/salon/services'
    | '/salon/settings'
    | '/salon/staff'
    | '/salon/wallet'
    | '/salon'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/salon'
    | '/salon/bookings'
    | '/salon/gallery'
    | '/salon/help-support'
    | '/salon/privacy-policy'
    | '/salon/profile'
    | '/salon/services'
    | '/salon/settings'
    | '/salon/staff'
    | '/salon/wallet'
    | '/salon/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SalonRoute: typeof SalonRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salon': {
      id: '/salon'
      path: '/salon'
      fullPath: '/salon'
      preLoaderRoute: typeof SalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salon/': {
      id: '/salon/'
      path: '/'
      fullPath: '/salon/'
      preLoaderRoute: typeof SalonIndexRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/wallet': {
      id: '/salon/wallet'
      path: '/wallet'
      fullPath: '/salon/wallet'
      preLoaderRoute: typeof SalonWalletRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/staff': {
      id: '/salon/staff'
      path: '/staff'
      fullPath: '/salon/staff'
      preLoaderRoute: typeof SalonStaffRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/settings': {
      id: '/salon/settings'
      path: '/settings'
      fullPath: '/salon/settings'
      preLoaderRoute: typeof SalonSettingsRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/services': {
      id: '/salon/services'
      path: '/services'
      fullPath: '/salon/services'
      preLoaderRoute: typeof SalonServicesRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/profile': {
      id: '/salon/profile'
      path: '/profile'
      fullPath: '/salon/profile'
      preLoaderRoute: typeof SalonProfileRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/privacy-policy': {
      id: '/salon/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/salon/privacy-policy'
      preLoaderRoute: typeof SalonPrivacyPolicyRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/help-support': {
      id: '/salon/help-support'
      path: '/help-support'
      fullPath: '/salon/help-support'
      preLoaderRoute: typeof SalonHelpSupportRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/gallery': {
      id: '/salon/gallery'
      path: '/gallery'
      fullPath: '/salon/gallery'
      preLoaderRoute: typeof SalonGalleryRouteImport
      parentRoute: typeof SalonRoute
    }
    '/salon/bookings': {
      id: '/salon/bookings'
      path: '/bookings'
      fullPath: '/salon/bookings'
      preLoaderRoute: typeof SalonBookingsRouteImport
      parentRoute: typeof SalonRoute
    }
  }
}

interface SalonRouteChildren {
  SalonBookingsRoute: typeof SalonBookingsRoute
  SalonGalleryRoute: typeof SalonGalleryRoute
  SalonHelpSupportRoute: typeof SalonHelpSupportRoute
  SalonPrivacyPolicyRoute: typeof SalonPrivacyPolicyRoute
  SalonProfileRoute: typeof SalonProfileRoute
  SalonServicesRoute: typeof SalonServicesRoute
  SalonSettingsRoute: typeof SalonSettingsRoute
  SalonStaffRoute: typeof SalonStaffRoute
  SalonWalletRoute: typeof SalonWalletRoute
  SalonIndexRoute: typeof SalonIndexRoute
}

const SalonRouteChildren: SalonRouteChildren = {
  SalonBookingsRoute: SalonBookingsRoute,
  SalonGalleryRoute: SalonGalleryRoute,
  SalonHelpSupportRoute: SalonHelpSupportRoute,
  SalonPrivacyPolicyRoute: SalonPrivacyPolicyRoute,
  SalonProfileRoute: SalonProfileRoute,
  SalonServicesRoute: SalonServicesRoute,
  SalonSettingsRoute: SalonSettingsRoute,
  SalonStaffRoute: SalonStaffRoute,
  SalonWalletRoute: SalonWalletRoute,
  SalonIndexRoute: SalonIndexRoute,
}

const SalonRouteWithChildren = SalonRoute._addFileChildren(SalonRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SalonRoute: SalonRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
